#!/usr/bin/env bash
# a script that displays Best School 10x.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER+=1))
done
